# GitHub Pages - Static Site (No Jekyll Processing)
# The .nojekyll file disables Jekyll processing
# This ensures JavaScript files are served as-is

title: "Sprint Prioritization Form"
description: "Web-based survey form for sprint prioritization with AWS integration"
